language: node_js
branches:
  only:
    - develop
    - master
node_js:
  - stable
services:
  - postgresql
install:
  - npm install
before_script:
  - psql -c "CREATE DATABASE ireportertestdb;" -U postgres
  - psql -c "CREATE USER ireportertest WITH PASSWORD 'ireportertest123';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE ireportertestdb to ireportertest;" -U postgres
script:
  - npm test
cache: 
  - npm install
after_success:
  - npm run coverage
env:
  global:
  - touch .env
  - echo TEST_DB_USERNAME=ireportertest >> .env
  - echo TEST_DB_PASSWORD=ireportertest123 >> .env
  - echo TEST_DB_DATABASE=ireportertestdb >> .env
  - echo TEST_DB_HOST='localhost' >> .env
  - echo TEST_DB_HOST=5432 >> .env
  - echo SECRET=somescret >> .env
