language: node_js
branches:
  only:
    - develop
    - master
node_js:
  - stable
services:
  - postgresql
install:
  - npm install
before_script:
  - psql -c "CREATE DATABASE ireporterdb;" -U postgres
  - psql -c "CREATE USER ireporter WITH PASSWORD 'ireporter123';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE ireporterdb to ireporter;" -U postgres
script:
  - npm test
cache: 
  - npm install
after_success:
  - npm run coverage
env:
  global:
  - touch .env
  - echo DATABASE_URL=postgres://ireporter:ireporter123@localhost:5432/ireporterdb >> .env
  - echo JWT_SECRET=somesecretfortest >> .env
